# Generated by Django 6.0.3 on 2026-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='colour',
            field=models.CharField(choices=[('#ef4444', 'Red'), ('#3b82f6', 'Blue'), ('#22c55e', 'Green'), ('#f59e0b', 'Yellow'), ('#a855f7', 'Purple'), ('#ec4899', 'Pink')], max_length=20),
        ),
    ]
