# Generated by Django 6.0.3 on 2026-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='dice_value',
        ),
        migrations.AddField(
            model_name='reward',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
