# Generated by Django 6.0.3 on 2026-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_reward_dice_value_reward_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='parent_pin',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
