# Generated by Django 6.0.3 on 2026-03-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_family_parent_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-created_at']},
        ),
    ]
